apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-kibana-pvc
  namespace: k3s-elk
  labels:
    app: elk-kibana
    component: kibana
spec:
  storageClassName: kibana-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      component: kibana
