apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elk-logstash
  namespace: k3s-elk
  labels:
    app: elk-logstash
    component: logstash
spec:
  serviceName: elk-logstash-headless
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app: elk-logstash
  template:
    metadata:
      labels:
        app: elk-logstash
        component: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.10.2
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 5044
          name: beats
        volumeMounts:
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
        - name: logstash-data
          mountPath: /usr/share/logstash/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 5044
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5044
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: pipeline
        configMap:
          name: elk-logstash-pipeline
  volumeClaimTemplates:
  - metadata:
      name: logstash-data
    spec:
      storageClassName: logstash-local-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
