apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: k3s-elk-stack
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30561
    name: http
