apiVersion: v1
kind: Service
metadata:
  name: elk-elasticsearch-nodeport
  namespace: k3s-elk
  labels:
    app: elk-elasticsearch
    component: elasticsearch
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: elk-elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 30920
