apiVersion: v1
kind: Service
metadata:
  name: elk-kibana-nodeport
  namespace: k3s-elk
  labels:
    app: elk-kibana
    component: kibana
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: elk-kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      nodePort: 30561
