apiVersion: v1
kind: Service
metadata:
  name: elk-logstash-nodeport
  namespace: k3s-elk
  labels:
    app: elk-logstash
    component: logstash
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: elk-logstash
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
      nodePort: 30044
