apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: k3s-elk-stack
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - port: 5044
    targetPort: 5044
    nodePort: 30044
    name: beats
