apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
  namespace: k3s-elk-stack
spec:
  serviceName: logstash-headless
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.10.2
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 5044
          name: beats
        volumeMounts:
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
        - name: logstash-data
          mountPath: /usr/share/logstash/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: pipeline
        configMap:
          name: logstash-pipeline
  volumeClaimTemplates:
  - metadata:
      name: logstash-data
    spec:
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
