apiVersion: v1
kind: Service
metadata:
  name: elk-elasticsearch-headless
  namespace: k3s-elk
  labels:
    app: elk-elasticsearch
    component: elasticsearch
    service-type: headless
spec:
  clusterIP: None
  selector:
    app: elk-elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
